### ISSUE TITLE
Отсутствует класс

### ISSUE THREAD

**Issue by eshimischi** [Vampiref92/BitrixBase#3]
https://github.com/Vampiref92/BitrixBase/blob/81210d51a520b5cd8a878429cd95aae1daeabb76/src/BitrixUtils/Orm/Model/User.php#L5

данный класс не существует, он по идее должен быть или ?

**Comment by Vampiref92** [comment]
это автогенерируемый класс. собирается чреез команду аннотаций Битрикса.

**Comment by eshimischi** [comment]
> это автогенерируемый класс. собирается чреез команду аннотаций Битрикса.

точно, благодарю за напоминание!
